"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  getSchedulesService,
  getMyDoctorSchedulesService,
  createMyDoctorScheduleService,
  deleteMyDoctorScheduleService,
} from "@/src/services/schedule.services";
import { ISchedule, IDoctorSchedule } from "@/src/types/domain.types";
import { Button } from "@/src/components/ui/button";
import { Clock, Calendar, Plus, Trash2, CheckCircle2, AlertCircle } from "lucide-react";

export default function DoctorMySchedulesPage() {
  const queryClient = useQueryClient();
  const [selectedScheduleIds, setSelectedScheduleIds] = useState<string[]>([]);
  const [msg, setMsg] = useState<string | null>(null);

  // Master Schedules created by Admin
  const { data: masterSchedulesResponse } = useQuery({
    queryKey: ["master-schedules"],
    queryFn: () => getSchedulesService({ limit: 50 }),
  });

  // Doctor's assigned schedules
  const { data: mySchedulesResponse, isLoading } = useQuery({
    queryKey: ["my-doctor-schedules"],
    queryFn: () => getMyDoctorSchedulesService({ limit: 50 }),
  });

  const masterSchedules = (masterSchedulesResponse && "data" in masterSchedulesResponse ? masterSchedulesResponse.data : []) as ISchedule[];
  const myDoctorSchedules = (mySchedulesResponse && "data" in mySchedulesResponse ? mySchedulesResponse.data : []) as IDoctorSchedule[];

  const assignMutation = useMutation({
    mutationFn: createMyDoctorScheduleService,
    onSuccess: (res) => {
      if ("success" in res && !res.success) {
        setMsg(res.message);
      } else {
        setMsg("Schedule slots assigned successfully!");
        setSelectedScheduleIds([]);
        queryClient.invalidateQueries({ queryKey: ["my-doctor-schedules"] });
      }
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (scheduleId: string) => deleteMyDoctorScheduleService(scheduleId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["my-doctor-schedules"] });
    },
  });

  const toggleScheduleSelect = (id: string) => {
    if (selectedScheduleIds.includes(id)) {
      setSelectedScheduleIds(selectedScheduleIds.filter((item) => item !== id));
    } else {
      setSelectedScheduleIds([...selectedScheduleIds, id]);
    }
  };

  const handleAssignSubmit = () => {
    if (selectedScheduleIds.length === 0) return;
    assignMutation.mutate({ scheduleIds: selectedScheduleIds });
  };

  const assignedScheduleIds = myDoctorSchedules.map((s) => s.scheduleId);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-foreground tracking-tight">Doctor Consultation Schedules</h1>
        <p className="text-xs text-muted-foreground mt-1">Assign master time slots to your active clinical practice</p>
      </div>

      {msg && <div className="p-3 bg-accent text-accent-foreground rounded-xl text-xs font-semibold">{msg}</div>}

      {/* Select & Assign Master Slots */}
      <div className="bg-card text-card-foreground rounded-3xl border border-border p-6 space-y-4 shadow-xs">
        <div className="flex items-center justify-between">
          <h3 className="font-bold text-foreground text-base flex items-center gap-2">
            <Clock className="h-5 w-5 text-primary" /> Assign Master Time Slots
          </h3>
          <Button
            size="sm"
            onClick={handleAssignSubmit}
            disabled={selectedScheduleIds.length === 0 || assignMutation.isPending}
            className="rounded-xl gap-2 text-xs"
          >
            <Plus className="h-4 w-4" />
            {assignMutation.isPending ? "Assigning..." : `Assign Selected (${selectedScheduleIds.length})`}
          </Button>
        </div>

        {masterSchedules.length === 0 ? (
          <p className="text-xs text-muted-foreground">No master schedules generated by Admin yet.</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 max-h-60 overflow-y-auto pr-1">
            {masterSchedules.map((slot) => {
              const isAlreadyAssigned = assignedScheduleIds.includes(slot.id);
              const isSelected = selectedScheduleIds.includes(slot.id);

              return (
                <button
                  key={slot.id}
                  type="button"
                  disabled={isAlreadyAssigned}
                  onClick={() => toggleScheduleSelect(slot.id)}
                  className={`p-3 rounded-xl border text-left text-xs transition-all ${
                    isAlreadyAssigned
                      ? "border-border bg-accent/30 opacity-50 cursor-not-allowed text-muted-foreground"
                      : isSelected
                      ? "border-primary bg-primary/10 font-bold text-primary ring-2 ring-primary/20"
                      : "border-border bg-card hover:bg-accent text-foreground"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold">{slot.startDate}</span>
                    {isAlreadyAssigned && <span className="text-[10px] bg-accent text-muted-foreground px-2 py-0.5 rounded-full">Assigned</span>}
                  </div>
                  <p className="text-[11px] text-muted-foreground mt-1">{slot.startTime} - {slot.endTime}</p>
                </button>
              );
            })}
          </div>
        )}
      </div>

      {/* Currently Assigned Doctor Schedules */}
      <div className="bg-card text-card-foreground rounded-3xl border border-border p-6 space-y-4 shadow-xs">
        <h3 className="font-bold text-foreground text-base">My Active Assigned Schedule Slots</h3>

        {isLoading ? (
          <div className="py-8 text-center text-xs text-muted-foreground">Loading schedule assignments...</div>
        ) : myDoctorSchedules.length === 0 ? (
          <div className="p-8 text-center bg-accent/30 rounded-2xl border border-dashed border-border text-xs text-muted-foreground">
            You haven&apos;t assigned any schedule slots yet. Select slots above to start receiving patient bookings.
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {myDoctorSchedules.map((ds) => (
              <div key={ds.scheduleId} className="bg-accent/40 border border-border rounded-2xl p-4 flex items-center justify-between">
                <div>
                  <p className="font-bold text-foreground text-xs">{ds.schedule?.startDate}</p>
                  <p className="text-[11px] text-muted-foreground mt-0.5">{ds.schedule?.startTime} - {ds.schedule?.endTime}</p>
                  <span
                    className={`inline-block mt-2 text-[10px] font-extrabold px-2 py-0.5 rounded-full ${
                      ds.isBooked ? "bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20" : "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20"
                    }`}
                  >
                    {ds.isBooked ? "Booked" : "Available"}
                  </span>
                </div>

                {!ds.isBooked && (
                  <button
                    onClick={() => deleteMutation.mutate(ds.scheduleId)}
                    className="p-2 text-rose-500 hover:bg-rose-500/10 rounded-xl transition-colors"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}